image:
  tag: 2.10.5

#service:
#  spec:
#    loadBalancerIP: ${public_ip}
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-resource-group: ${resource_group_name}

rbac:
  enabled: true

ssl:
  enabled: true
  enforced: true

ports:
  web:
    redirectTo:
      port: "websecure"


persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {
    "pv.beta.kubernetes.io/gid": "65532"
  }

podSecurityContext:
  fsGroup: 65532

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "mkdir -p /data; touch /data/acme.json; chmod -Rv 600 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data

additionalArguments:
  - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8
  - --certificatesresolvers.le.acme.email=numpyme@gmail.com
  - --certificatesresolvers.le.acme.storage=/data/acme.json
  - --certificatesresolvers.le.acme.httpchallenge=true
  - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web


ingressRoute:
  dashboard:
    annotations:
      kubernetes.io/ingress.class: traefik

#metrics:
#  prometheus:
#    service:
#      enabled: true
#    entryPoint: metrics
#    addRoutersLabels: true
#    addEntryPointsLabels: true
#    addServicesLabels: true

#entryPoints:
#  metrics:
#    address: ":8080"
